spring:
  banner:
    location: classpath:/banner.txt
  profiles:
    default: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor
    hibernate:
      ddl-auto: validate
    open-in-view: true
  liquibase:
    change-log: classpath:/db/master.xml